### ISSUE TITLE
Null users are not checked for

### ISSUE THREAD

**Issue by mhucka** [caltechlibrary/dibs#36]
This may only happen in debug mode, but if REMOTE_USER is not set, server.py doesn't check for None and some things fail.

**Comment by rsdoiel** [comment]
Let's have a single function that does the REMOTE_USER check (I don't think I did that off the top of my head). That way we can make sure it returns predictables results. I am concerned that as DIBS evolves we might make assumptions and have forgotten an import edge case.

**Comment by rsdoiel** [comment]
I was thinking I should put that in the dibs/people.py module. Does that make sense?

**Comment by mhucka** [comment]
people.py should probably check for it, but the code in server.py also needs to check the value returned from person_from_environment(). 

Rather than put code to do that all over the place, I was thinking of exploring the use of Bottle hooks. Those get called before routes get called.

**Comment by rsdoiel** [comment]
That makes sense. I'm still learning Bottle so didn't think of that.

**Comment by mhucka** [comment]
I'm learning about it too! I didn't even know about hook functions until about a week ago, and used one in `run-server` to inject REMOTE_USER into request.environ when running in debug mode.

**Comment by rsdoiel** [comment]
Your idea of using the hook is the way to go. Our existing person_from_environment() does what it is supposed to do but we have sprinkled all over.  I suspect it probably is being called multiple times in some code paths and not in others. E.g. the "page" function calls it be that is called by views which also call that function.  If this is implemented with a Bottle hook we could insure it is called once per request, is that correct?

**Comment by mhucka** [comment]
I'm closing this since the relevant code has been merged and things seem to be working.
