### ISSUE TITLE
people-manager problems with paths and command output

### ISSUE THREAD

**Issue by mhucka** [caltechlibrary/dibs#43]
The code in `people.py` can pick up the wrong copies of htpasswd and the password file. It should probably have full paths to those things. Also, the way it checks for output from `htpasswd` can mislead it into think there is an error when there is not.

**Comment by rsdoiel** [comment]
I've improved people-manager, pushed most of the functions into a new class PersonManager in dibs/people.py. I've also dropped the "secret" column from person table. I've included "update_person_schema.sql" that will migrate to the new schema for an existing person table.

We can close the issue once the pull request is approved.
