### ISSUE TITLE
Mobile viewer configuration

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dibs#60]
The mobile UV viewer is missing some features that are available on desktop:

- No reservation timer
- No end loan button
- No contents panel
- Non-functional bookmark button - see screenshot (not present in desktop)

![IMG_3313](https://user-images.githubusercontent.com/10798874/116448810-5e4c4f80-a80e-11eb-993a-c073d5ad1638.jpg)

**Comment by mhucka** [comment]
Actually, I get the bookmark symbol on the desktop version too. I couldn't figure out what it was supposed to do, so I left it, in case the problem was that I didn't understand how to use the bookmarking feature.

We can take this out pretty easily in the config.

**Comment by t4k** [comment]
same issue for me with Brave Browser on Android

**Comment by tmorrell** [comment]
These changes look great to me. I don’t think there is a pressing need for the timer or contents panel.
