### ISSUE TITLE
Multibyte characters in title or author cause blank page

### ISSUE THREAD

**Issue by stanonik** [caltechlibrary/dibs#90]
We had to modify server.py to connect to our Ex Libris Alma, so maybe we introduced this problem.

If the Title or Author contain multibyte characters, then a loan only displays a blank page.

For example, this author
Yookoso! : continuing with contemporary Japanese = [Yōkoso]

**Comment by mhucka** [comment]
Thanks for this report. I'll take a look at the relevant parts and test with multibyte characters. This comes at a good time as I'm working on DIBS currently.

**Comment by stanonik** [comment]
Hi,
Thanks for the reply.
We found the following seems to work for us.
This wasn't the result of careful code reading, rather just a quick glimpse
to solve, first the open, then a length problem.
I realize now I used my personal email when I logged onto github, not my
work account.
Anyway, thanks for the code.
Ron Stanonik
***@***.***


--- a/dibs/server.py
+++ b/dibs/server.py
@@ -720,10 +720,10 @@ def return_iiif_manifest(barcode, person):
             log(f'{manifest_file} does not exist')
             return
         record_request(barcode)
-        with open(manifest_file, 'r') as mf:
+        with open(manifest_file, 'r', encoding='utf-8') as mf:
             adjusted_content = urls_rerouted(mf.read(), barcode)
             data = BytesIO(adjusted_content.encode())
-            size = len(adjusted_content)
+            size = len(adjusted_content.encode())
             log(f'returning manifest for {barcode} for
{anon(person.uname)}')
             return send_file(data, ctype = 'application/json', size = size)
     else:

**Comment by mhucka** [comment]
This is in commit f098ce6.

**Comment by mhucka** [comment]
@stanonik I'm having trouble finding a manifest file that I could use for testing this issue. I don't suppose you have something that you could share?  Even if the IIIF URLs didn't work in our site, it would still make it possible to try reading the file and trying to understand if other problems might still exist. If you don't want to upload it here but could share it privately, perhaps email it to me directly to mhucka@library.caltech.edu?

**Comment by mhucka** [comment]
Thanks for the example manifest file. Things seem to be working with that change, so I'm going ahead and closing this issue, but if necessary we can reopen it.
